const musicData = {
  data: [
    {
      ImageLocation:
        "assets/Music/Sreekaram Subhakaram/Sreekaram Subhakaram Front Cover.jpg",
      Album: "Sreekaram Subhakaram",
      Songs: [
        {
          songName: "Vandanamu",
          ragam: "Hamswadhwani",
          talam: "Adi talam",
          singer: "",
          fileName: "01 Vandanamu.mp3",
        },
        {
          songName: "Arudenche",
          ragam: "Bilahari",
          talam: "Adi talam",
          singer: "",
          fileName: "02 Arudenche .mp3",
        },
        {
          songName: "Manipura Vasini",
          ragam: "Keeravani",
          talam: "Adi talam",
          singer: "",
          fileName: "03 Manipura Vasini .mp3",
        },
        {
          songName: "Raghukula Thilaka",
          ragam: "Thillang",
          talam: "Eka talam",
          singer: "",
          fileName: "04 Raghukula Thilaka .mp3",
        },
        {
          songName: "Sailaraja Sutha",
          ragam: "ShanmukhaPriya",
          talam: "Adi talam",
          singer: "",
          fileName: "05 Sailaraja Sutha .mp3",
        },
        {
          songName: "Pranava Nadam",
          ragam: "Bhupalam",
          talam: "Thisragathi talam",
          singer: "",
          fileName: "06 Pranava Nadam .mp3",
        },
        {
          songName: "Ninu Nera Nammithi",
          ragam: "Bhageshwari",
          talam: "Adi talam",
          singer: "",
          fileName: "07 Ninu Nera Nammithi .mp3",
        },
        {
          songName: "Maaruthathmaja",
          ragam: "Dharmavathi",
          talam: "Thisra, Adi talam",
          singer: "",
          fileName: "08 Maaruthathmaja .mp3",
        },
        {
          songName: "Mangalam",
          ragam: "Madhyamavathi",
          talam: "Adi talam",
          singer: "",
          fileName: "09 Mangalam .mp3",
        },
      ],
    },

    {
      ImageLocation:
        "assets/Music/Sivapada Kinkinulu/Sivapada Kinkinulu Front Cover.jpeg",

      Album: "Sivapada Kinkinulu",
      Songs: [
        {
          songName: "Akhilandakoti",
          ragam: "",
          talam: "",
          singer: "G Balakrishna Prasad",
          fileName: "01 Akhilandakoti .mp3",
        },
        {
          songName: "Sivapadamantina",
          ragam: "",
          talam: "",
          singer: "Surekha, Nityasantoshini",
          fileName: "02 Sivapadamantina .mp3",
        },
        {
          songName: "Prudhvi Pedavi Vippi",
          ragam: "",
          talam: "",
          singer: "Dr S P Balasubrahmanyam",
          fileName: "03 Prudhvi Pedavi Vippi .mp3",
        },
        {
          songName: "Madi Haruni",
          ragam: "",
          talam: "",
          singer: "Surekha",
          fileName: "04 Madi Haruni .mp3",
        },
        {
          songName: "Padakinkini",
          ragam: "",
          talam: "",
          singer: "Ramachari and Chorus",
          fileName: "05 Padakinkini .mp3",
        },
        {
          songName: "Needu Pada",
          ragam: "",
          talam: "",
          singer: "G Balakrishna Prasad and Chorus",
          fileName: "06 Needu Pada .mp3",
        },
        {
          songName: "Kadali Kailasagiri",
          ragam: "",
          talam: "",
          singer: "Surekha and Ramachary",
          fileName: "07 Kadali Kailasagiri .mp3",
        },
        {
          songName: "Nitalaksha",
          ragam: "",
          talam: "",
          singer: "S P Balasubrahmanyam",
          fileName: "08 Nitalaksha .mp3",
        },
        {
          songName: "Kadali Kanniya",
          ragam: "",
          talam: "",
          singer: "Sunitha",
          fileName: "09 Kadali Kanniya .mp3",
        },
      ],
    },
    {
      ImageLocation:
        "assets/Music/Pranavanaadaalu/Pranavanaadalu Front Cover.jpeg",

      Album: "Pranavanaadaalu",
      Songs: [
        {
          songName: "Rateevilaapamu",
          ragam: "",
          talam: "",
          singer: "G.V Prabhar and Party",
          fileName: "01 Rateevilaapamu.mp3",
        },
        {
          songName: "Needu Paadamu",
          ragam: "",
          talam: "",
          singer: "U Shilpa",
          fileName: "02 Needu Paadamu .mp3",
        },
        {
          songName: "Okkokka Sikharame",
          ragam: "",
          talam: "",
          singer: "G V Prabhakar and M Soujanya",
          fileName: "03 Okkokka Sikharame .mp3",
        },
        {
          songName: "Viswavibhuni",
          ragam: "",
          talam: "",
          singer: "G V Prabhakar",
          fileName: "04 Viswavibhuni .mp3",
        },
        {
          songName: "Neekaali Muvvalu",
          ragam: "",
          talam: "",
          singer: "M Soujanya",
          fileName: "05 Neekaali Muvvalu .mp3",
        },
      ],
    },
    {
      ImageLocation: "assets/Music/Samarpayami/Samarpayami Back Cover.jpeg",

      Album: "Samarpayami",
      Songs: [
        {
          songName: "Saptaswarajhari",
          ragam: "",
          talam: "",
          singer: "Dr Balamuralikrishna",
          fileName: "01 Saptaswarajhari.mp3",
        },
        {
          songName: "Nava Vidha Bhakti",
          ragam: "",
          talam: "",
          singer: "Dr Balamuralikrishna",
          fileName: "02 Nava Vidha Bhakti.mp3",
        },
        {
          songName: "Adwiteeyam Sankhyakadanam",
          ragam: "",
          talam: "",
          singer: "Dr Balamuralikrishna",
          fileName: "03 Adwiteeyam Sankhyakadanam.mp3",
        },
      ],
    },
    {
      ImageLocation:
        "assets/Music/Sreekaram Subhakaram/Sreekaram Subhakaram Front Cover.jpg",

      Album: "Bhadradri Ramayya Swara Sumalu",
      Songs: [
        {
          songName: "Arunaarunakanthi",
          ragam: "Malayamarutham",
          talam: "",
          singer: "",
          fileName: "01 Arunaarunakanthi .mp3",
        },
        {
          songName: "Tharuni Seetha",
          ragam: "Hamir Kalyani",
          talam: "",
          singer: "",
          fileName: "02 Tharuni Seetha .mp3",
        },
        {
          songName: "Raghukula Thilaka",
          ragam: "Thillang",
          talam: "",
          singer: "",
          fileName: "03 Raghukula Thilaka .mp3",
        },
        {
          songName: "Dandalayya",
          ragam: "Hari Kamboji",
          talam: "",
          singer: "",
          fileName: "04 Dandalayya .mp3",
        },
        {
          songName: "Tholli Valmiki",
          ragam: "Brindavani",
          talam: "",
          singer: "",
          fileName: "05 Tholli Valmiki .mp3",
        },
        {
          songName: "Ninu Nera Nammithi",
          ragam: "Bhageswari",
          talam: "",
          singer: "",
          fileName: "06 Ninu Nera Nammithi .mp3",
        },
        {
          songName: "Bhadradri Raamude",
          ragam: "Amrutha Varshini",
          talam: "",
          singer: "",
          fileName: "07 Bhadradri Raamude .mp3",
        },
        {
          songName: "Mangalam",
          ragam: "Kuranji",
          talam: "",
          singer: "",
          fileName: "08 Mangalam .mp3",
        },
      ],
    },
    {
      ImageLocation:
        "assets/Music/Sreekaram Subhakaram/Sreekaram Subhakaram Front Cover.jpg",

      Album: "Hari Villu",
      Songs: [
        {
          songName: "Introduction",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "01 Introduction.mp3",
        },
        {
          songName: "Akhilanda",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "02 Akhilanda.mp3",
        },
        {
          songName: "Sukkalatho",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "03 Sukkalatho.mp3",
        },
        {
          songName: "Palukulo Thene",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "04 Palukulo Thene.mp3",
        },
        {
          songName: "Murali Nandina",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "05 Murali Nandina.mp3",
        },
        {
          songName: "Mamathalu",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "06 Mamathalu.mp3",
        },
        {
          songName: "Vachindi Vasantham",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "07 Vachindi Vasantham.mp3",
        },
        {
          songName: "Valupu Chinuku",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "08 Valupu Chinuku.mp3",
        },
        {
          songName: "Chinni Navula",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "09 Chinni Navula.mp3",
        },
        {
          songName: "Nee Vegu Daarilo",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "10 Nee Vegu Daarilo.mp3",
        },
        {
          songName: "Vanne Vannela",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "11 Vanne Vannela.mp3",
        },
        {
          songName: "Movi Nantina",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "12 Movi Nantina.mp3",
        },
        {
          songName: "Siva pada",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "13 Siva pada.mp3",
        },
      ],
    },
    {
      ImageLocation:
        "assets/Music/Sreekaram Subhakaram/Sreekaram Subhakaram Front Cover.jpg",

      Album: "Venu Ravaalu",
      Songs: [
        {
          songName: "Challa Gaali",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "01 Challa Gaali.mp3",
        },
        {
          songName: "Jaalu Vare",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "02 Jaalu Vare.mp3",
        },
        {
          songName: "Chirunavvu",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "03 Chirunavvu.mp3",
        },
        {
          songName: "Velugula",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "04 Velugula.mp3",
        },
        {
          songName: "Yeda Podarillu",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "05 Yeda Podarillu.mp3",
        },
        {
          songName: "Punnaga",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "06 Punnaga.mp3",
        },
        {
          songName: "Paluku Paluki",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "07 Paluku Paluki.mp3",
        },
        {
          songName: "Chaitramasapu",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "08 Chaitramasapu.mp3",
        },
        {
          songName: "Gaganala",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "09 Gaganala.mp3",
        },
        {
          songName: "Yededu Kondalu",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "10 Yededu Kondalu.mp3",
        },
      ],
    },
    {
      ImageLocation:
        "assets/Music/Sreekaram Subhakaram/Sreekaram Subhakaram Front Cover.jpg",

      Album: "Gaali Pallaki Kavithalu",
      Songs: [
        {
          songName: "Gaalipallaki Kavithalu",
          ragam: "",
          talam: "",
          singer: "",
          fileName: "01 GaalipallakiKavithalu.mp3",
        },
      ],
    },
  ],
};

export default musicData;